// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkamessage.proto

// Protobuf Java Version: 3.25.1
package com.example.webfluxStudy.entity;

public interface FruitMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.webfluxStudy.entity.FruitMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1 [default = "default id"];</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 1 [default = "default id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1 [default = "default id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string message = 2 [default = "this is default message"];</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 2 [default = "this is default message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2 [default = "this is default message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
