// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inheritance4.proto

// Protobuf Java Version: 3.25.1
package com.example.webfluxStudy.entity.protoExample.Inheritance;

public interface BirdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animals.Bird)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   * @return The msg.
   */
  com.google.protobuf.Any getMsg();
  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getMsgOrBuilder();

  /**
   * <code>bool can_fly = 2;</code>
   * @return The canFly.
   */
  boolean getCanFly();
}
