// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inheritance4.proto

// Protobuf Java Version: 3.25.1
package com.example.webfluxStudy.entity.protoExample.Inheritance;

/**
 * Protobuf type {@code animals.Dog}
 */
public final class Dog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:animals.Dog)
    DogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Dog.newBuilder() to construct.
  private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Dog() {
    breed_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Dog();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance4.internal_static_animals_Dog_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance4.internal_static_animals_Dog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.webfluxStudy.entity.protoExample.Inheritance.Dog.class, com.example.webfluxStudy.entity.protoExample.Inheritance.Dog.Builder.class);
  }

  private int bitField0_;
  public static final int MSG_FIELD_NUMBER = 1;
  private com.google.protobuf.Any msg_;
  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   * @return Whether the msg field is set.
   */
  @java.lang.Override
  public boolean hasMsg() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   * @return The msg.
   */
  @java.lang.Override
  public com.google.protobuf.Any getMsg() {
    return msg_ == null ? com.google.protobuf.Any.getDefaultInstance() : msg_;
  }
  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getMsgOrBuilder() {
    return msg_ == null ? com.google.protobuf.Any.getDefaultInstance() : msg_;
  }

  public static final int BREED_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object breed_ = "";
  /**
   * <code>string breed = 2;</code>
   * @return The breed.
   */
  @java.lang.Override
  public java.lang.String getBreed() {
    java.lang.Object ref = breed_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      breed_ = s;
      return s;
    }
  }
  /**
   * <code>string breed = 2;</code>
   * @return The bytes for breed.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBreedBytes() {
    java.lang.Object ref = breed_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      breed_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMsg());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(breed_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, breed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMsg());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(breed_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, breed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.webfluxStudy.entity.protoExample.Inheritance.Dog)) {
      return super.equals(obj);
    }
    com.example.webfluxStudy.entity.protoExample.Inheritance.Dog other = (com.example.webfluxStudy.entity.protoExample.Inheritance.Dog) obj;

    if (hasMsg() != other.hasMsg()) return false;
    if (hasMsg()) {
      if (!getMsg()
          .equals(other.getMsg())) return false;
    }
    if (!getBreed()
        .equals(other.getBreed())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMsg()) {
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
    }
    hash = (37 * hash) + BREED_FIELD_NUMBER;
    hash = (53 * hash) + getBreed().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.webfluxStudy.entity.protoExample.Inheritance.Dog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code animals.Dog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:animals.Dog)
      com.example.webfluxStudy.entity.protoExample.Inheritance.DogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance4.internal_static_animals_Dog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance4.internal_static_animals_Dog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.webfluxStudy.entity.protoExample.Inheritance.Dog.class, com.example.webfluxStudy.entity.protoExample.Inheritance.Dog.Builder.class);
    }

    // Construct using com.example.webfluxStudy.entity.protoExample.Inheritance.Dog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMsgFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      msg_ = null;
      if (msgBuilder_ != null) {
        msgBuilder_.dispose();
        msgBuilder_ = null;
      }
      breed_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance4.internal_static_animals_Dog_descriptor;
    }

    @java.lang.Override
    public com.example.webfluxStudy.entity.protoExample.Inheritance.Dog getDefaultInstanceForType() {
      return com.example.webfluxStudy.entity.protoExample.Inheritance.Dog.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.webfluxStudy.entity.protoExample.Inheritance.Dog build() {
      com.example.webfluxStudy.entity.protoExample.Inheritance.Dog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.webfluxStudy.entity.protoExample.Inheritance.Dog buildPartial() {
      com.example.webfluxStudy.entity.protoExample.Inheritance.Dog result = new com.example.webfluxStudy.entity.protoExample.Inheritance.Dog(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.webfluxStudy.entity.protoExample.Inheritance.Dog result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.msg_ = msgBuilder_ == null
            ? msg_
            : msgBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.breed_ = breed_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.webfluxStudy.entity.protoExample.Inheritance.Dog) {
        return mergeFrom((com.example.webfluxStudy.entity.protoExample.Inheritance.Dog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.webfluxStudy.entity.protoExample.Inheritance.Dog other) {
      if (other == com.example.webfluxStudy.entity.protoExample.Inheritance.Dog.getDefaultInstance()) return this;
      if (other.hasMsg()) {
        mergeMsg(other.getMsg());
      }
      if (!other.getBreed().isEmpty()) {
        breed_ = other.breed_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMsgFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              breed_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Any msg_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> msgBuilder_;
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     * @return Whether the msg field is set.
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     * @return The msg.
     */
    public com.google.protobuf.Any getMsg() {
      if (msgBuilder_ == null) {
        return msg_ == null ? com.google.protobuf.Any.getDefaultInstance() : msg_;
      } else {
        return msgBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     */
    public Builder setMsg(com.google.protobuf.Any value) {
      if (msgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
      } else {
        msgBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     */
    public Builder setMsg(
        com.google.protobuf.Any.Builder builderForValue) {
      if (msgBuilder_ == null) {
        msg_ = builderForValue.build();
      } else {
        msgBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     */
    public Builder mergeMsg(com.google.protobuf.Any value) {
      if (msgBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          msg_ != null &&
          msg_ != com.google.protobuf.Any.getDefaultInstance()) {
          getMsgBuilder().mergeFrom(value);
        } else {
          msg_ = value;
        }
      } else {
        msgBuilder_.mergeFrom(value);
      }
      if (msg_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     */
    public Builder clearMsg() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msg_ = null;
      if (msgBuilder_ != null) {
        msgBuilder_.dispose();
        msgBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     */
    public com.google.protobuf.Any.Builder getMsgBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getMsgOrBuilder() {
      if (msgBuilder_ != null) {
        return msgBuilder_.getMessageOrBuilder();
      } else {
        return msg_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : msg_;
      }
    }
    /**
     * <code>.google.protobuf.Any msg = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getMsgFieldBuilder() {
      if (msgBuilder_ == null) {
        msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getMsg(),
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      return msgBuilder_;
    }

    private java.lang.Object breed_ = "";
    /**
     * <code>string breed = 2;</code>
     * @return The breed.
     */
    public java.lang.String getBreed() {
      java.lang.Object ref = breed_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        breed_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string breed = 2;</code>
     * @return The bytes for breed.
     */
    public com.google.protobuf.ByteString
        getBreedBytes() {
      java.lang.Object ref = breed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        breed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string breed = 2;</code>
     * @param value The breed to set.
     * @return This builder for chaining.
     */
    public Builder setBreed(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      breed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string breed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBreed() {
      breed_ = getDefaultInstance().getBreed();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string breed = 2;</code>
     * @param value The bytes for breed to set.
     * @return This builder for chaining.
     */
    public Builder setBreedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      breed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:animals.Dog)
  }

  // @@protoc_insertion_point(class_scope:animals.Dog)
  private static final com.example.webfluxStudy.entity.protoExample.Inheritance.Dog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.webfluxStudy.entity.protoExample.Inheritance.Dog();
  }

  public static com.example.webfluxStudy.entity.protoExample.Inheritance.Dog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Dog>
      PARSER = new com.google.protobuf.AbstractParser<Dog>() {
    @java.lang.Override
    public Dog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Dog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Dog> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.webfluxStudy.entity.protoExample.Inheritance.Dog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

