// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inheritance4.proto

// Protobuf Java Version: 3.25.1
package com.example.webfluxStudy.entity.protoExample.Inheritance;

public interface DogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:animals.Dog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   * @return The msg.
   */
  com.google.protobuf.Any getMsg();
  /**
   * <code>.google.protobuf.Any msg = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getMsgOrBuilder();

  /**
   * <code>string breed = 2;</code>
   * @return The breed.
   */
  java.lang.String getBreed();
  /**
   * <code>string breed = 2;</code>
   * @return The bytes for breed.
   */
  com.google.protobuf.ByteString
      getBreedBytes();
}
