// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inheritance1.proto

// Protobuf Java Version: 3.25.1
package com.example.webfluxStudy.entity.protoExample.Inheritance;

public final class Inheritance1 {

    private Inheritance1() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface AnimalOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();
    }

    /**
     * Protobuf type {@code com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal}
     */
    public static final class Animal extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal)
        AnimalOrBuilder {

        private static final long serialVersionUID = 0L;

        // Use Animal.newBuilder() to construct.
        private Animal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Animal() {
            name_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
            return new Animal();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.class,
                    com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object name_ = "";

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) {
            return true;
          }
          if (isInitialized == 0) {
            return false;
          }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
          if (size != -1) {
            return size;
          }

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal)) {
                return super.equals(obj);
            }
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal other = (com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal) obj;

          if (!getName()
              .equals(other.getName())) {
            return false;
          }
          if (!getUnknownFields().equals(other.getUnknownFields())) {
            return false;
          }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseDelimitedFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal)
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.class,
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder.class);
            }

            // Construct using com.example.webfluxStudy.entity.protoExample.Inheritance1.Inheritance1.Animal.newBuilder()
            private Builder() {

            }

            private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                name_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_descriptor;
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getDefaultInstanceForType() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance();
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal build() {
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal buildPartial() {
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal result = new com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal(
                    this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.name_ = name_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal) {
                    return mergeFrom(
                        (com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal other) {
              if (other
                  == com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()) {
                return this;
              }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                name_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object name_ = "";

            /**
             * <code>string name = 1;</code>
             *
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                name_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {
                name_ = getDefaultInstance().getName();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                name_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal)
        }

        // @@protoc_insertion_point(class_scope:com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal)
        private static final com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal();
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Animal>
            PARSER = new com.google.protobuf.AbstractParser<Animal>() {
            @java.lang.Override
            public Animal parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException()
                        .setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Animal> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Animal> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface BirdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.example.webfluxStudy.entity.protoExample.Inheritance1.Bird)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         *
         * @return Whether the animal field is set.
         */
        boolean hasAnimal();

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         *
         * @return The animal.
         */
        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getAnimal();

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         */
        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder getAnimalOrBuilder();

        /**
         * <code>bool can_fly = 2;</code>
         *
         * @return The canFly.
         */
        boolean getCanFly();
    }

    /**
     * Protobuf type {@code com.example.webfluxStudy.entity.protoExample.Inheritance1.Bird}
     */
    public static final class Bird extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.example.webfluxStudy.entity.protoExample.Inheritance1.Bird)
        BirdOrBuilder {

        private static final long serialVersionUID = 0L;

        // Use Bird.newBuilder() to construct.
        private Bird(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Bird() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
            return new Bird();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird.class,
                    com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird.Builder.class);
        }

        private int bitField0_;
        public static final int ANIMAL_FIELD_NUMBER = 1;
        private com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal animal_;

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         *
         * @return Whether the animal field is set.
         */
        @java.lang.Override
        public boolean hasAnimal() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         *
         * @return The animal.
         */
        @java.lang.Override
        public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getAnimal() {
            return animal_ == null
                ? com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()
                : animal_;
        }

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         */
        @java.lang.Override
        public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder getAnimalOrBuilder() {
            return animal_ == null
                ? com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()
                : animal_;
        }

        public static final int CAN_FLY_FIELD_NUMBER = 2;
        private boolean canFly_ = false;

        /**
         * <code>bool can_fly = 2;</code>
         *
         * @return The canFly.
         */
        @java.lang.Override
        public boolean getCanFly() {
            return canFly_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) {
            return true;
          }
          if (isInitialized == 0) {
            return false;
          }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(1, getAnimal());
            }
            if (canFly_ != false) {
                output.writeBool(2, canFly_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
          if (size != -1) {
            return size;
          }

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getAnimal());
            }
            if (canFly_ != false) {
                size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(2, canFly_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird)) {
                return super.equals(obj);
            }
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird other = (com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird) obj;

          if (hasAnimal() != other.hasAnimal()) {
            return false;
          }
            if (hasAnimal()) {
              if (!getAnimal()
                  .equals(other.getAnimal())) {
                return false;
              }
            }
          if (getCanFly()
              != other.getCanFly()) {
            return false;
          }
          if (!getUnknownFields().equals(other.getUnknownFields())) {
            return false;
          }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasAnimal()) {
                hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
                hash = (53 * hash) + getAnimal().hashCode();
            }
            hash = (37 * hash) + CAN_FLY_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getCanFly());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseDelimitedFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.example.webfluxStudy.entity.protoExample.Inheritance1.Bird}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.example.webfluxStudy.entity.protoExample.Inheritance1.Bird)
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.BirdOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird.class,
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird.Builder.class);
            }

            // Construct using com.example.webfluxStudy.entity.protoExample.Inheritance1.Inheritance1.Bird.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                    getAnimalFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                animal_ = null;
                if (animalBuilder_ != null) {
                    animalBuilder_.dispose();
                    animalBuilder_ = null;
                }
                canFly_ = false;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_descriptor;
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird getDefaultInstanceForType() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird.getDefaultInstance();
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird build() {
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird buildPartial() {
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird result = new com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird(
                    this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.animal_ = animalBuilder_ == null
                        ? animal_
                        : animalBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.canFly_ = canFly_;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird) {
                    return mergeFrom(
                        (com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird other) {
              if (other
                  == com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird.getDefaultInstance()) {
                return this;
              }
                if (other.hasAnimal()) {
                    mergeAnimal(other.getAnimal());
                }
                if (other.getCanFly() != false) {
                    setCanFly(other.getCanFly());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                input.readMessage(
                                    getAnimalFieldBuilder().getBuilder(),
                                    extensionRegistry);
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 16: {
                                canFly_ = input.readBool();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal animal_;
            private com.google.protobuf.SingleFieldBuilderV3<
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder> animalBuilder_;

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             *
             * @return Whether the animal field is set.
             */
            public boolean hasAnimal() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             *
             * @return The animal.
             */
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getAnimal() {
                if (animalBuilder_ == null) {
                    return animal_ == null
                        ? com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()
                        : animal_;
                } else {
                    return animalBuilder_.getMessage();
                }
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public Builder setAnimal(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal value) {
                if (animalBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    animal_ = value;
                } else {
                    animalBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public Builder setAnimal(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder builderForValue) {
                if (animalBuilder_ == null) {
                    animal_ = builderForValue.build();
                } else {
                    animalBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public Builder mergeAnimal(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal value) {
                if (animalBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0) &&
                        animal_ != null &&
                        animal_
                            != com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()) {
                        getAnimalBuilder().mergeFrom(value);
                    } else {
                        animal_ = value;
                    }
                } else {
                    animalBuilder_.mergeFrom(value);
                }
                if (animal_ != null) {
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public Builder clearAnimal() {
                bitField0_ = (bitField0_ & ~0x00000001);
                animal_ = null;
                if (animalBuilder_ != null) {
                    animalBuilder_.dispose();
                    animalBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder getAnimalBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getAnimalFieldBuilder().getBuilder();
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder getAnimalOrBuilder() {
                if (animalBuilder_ != null) {
                    return animalBuilder_.getMessageOrBuilder();
                } else {
                    return animal_ == null ?
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()
                        : animal_;
                }
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder>
            getAnimalFieldBuilder() {
                if (animalBuilder_ == null) {
                    animalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder>(
                        getAnimal(),
                        getParentForChildren(),
                        isClean());
                    animal_ = null;
                }
                return animalBuilder_;
            }

            private boolean canFly_;

            /**
             * <code>bool can_fly = 2;</code>
             *
             * @return The canFly.
             */
            @java.lang.Override
            public boolean getCanFly() {
                return canFly_;
            }

            /**
             * <code>bool can_fly = 2;</code>
             *
             * @param value The canFly to set.
             * @return This builder for chaining.
             */
            public Builder setCanFly(boolean value) {

                canFly_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>bool can_fly = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCanFly() {
                bitField0_ = (bitField0_ & ~0x00000002);
                canFly_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:com.example.webfluxStudy.entity.protoExample.Inheritance1.Bird)
        }

        // @@protoc_insertion_point(class_scope:com.example.webfluxStudy.entity.protoExample.Inheritance1.Bird)
        private static final com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird();
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Bird>
            PARSER = new com.google.protobuf.AbstractParser<Bird>() {
            @java.lang.Override
            public Bird parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException()
                        .setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Bird> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Bird> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Bird getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface DogOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.example.webfluxStudy.entity.protoExample.Inheritance1.Dog)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         *
         * @return Whether the animal field is set.
         */
        boolean hasAnimal();

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         *
         * @return The animal.
         */
        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getAnimal();

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         */
        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder getAnimalOrBuilder();

        /**
         * <code>string breed = 2;</code>
         *
         * @return The breed.
         */
        java.lang.String getBreed();

        /**
         * <code>string breed = 2;</code>
         *
         * @return The bytes for breed.
         */
        com.google.protobuf.ByteString
        getBreedBytes();
    }

    /**
     * Protobuf type {@code com.example.webfluxStudy.entity.protoExample.Inheritance1.Dog}
     */
    public static final class Dog extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.example.webfluxStudy.entity.protoExample.Inheritance1.Dog)
        DogOrBuilder {

        private static final long serialVersionUID = 0L;

        // Use Dog.newBuilder() to construct.
        private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Dog() {
            breed_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
            return new Dog();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog.class,
                    com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog.Builder.class);
        }

        private int bitField0_;
        public static final int ANIMAL_FIELD_NUMBER = 1;
        private com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal animal_;

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         *
         * @return Whether the animal field is set.
         */
        @java.lang.Override
        public boolean hasAnimal() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         *
         * @return The animal.
         */
        @java.lang.Override
        public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getAnimal() {
            return animal_ == null
                ? com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()
                : animal_;
        }

        /**
         * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
         * 1;</code>
         */
        @java.lang.Override
        public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder getAnimalOrBuilder() {
            return animal_ == null
                ? com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()
                : animal_;
        }

        public static final int BREED_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object breed_ = "";

        /**
         * <code>string breed = 2;</code>
         *
         * @return The breed.
         */
        @java.lang.Override
        public java.lang.String getBreed() {
            java.lang.Object ref = breed_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                breed_ = s;
                return s;
            }
        }

        /**
         * <code>string breed = 2;</code>
         *
         * @return The bytes for breed.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getBreedBytes() {
            java.lang.Object ref = breed_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                breed_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) {
            return true;
          }
          if (isInitialized == 0) {
            return false;
          }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(1, getAnimal());
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(breed_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, breed_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
          if (size != -1) {
            return size;
          }

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getAnimal());
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(breed_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, breed_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog)) {
                return super.equals(obj);
            }
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog other = (com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog) obj;

          if (hasAnimal() != other.hasAnimal()) {
            return false;
          }
            if (hasAnimal()) {
              if (!getAnimal()
                  .equals(other.getAnimal())) {
                return false;
              }
            }
          if (!getBreed()
              .equals(other.getBreed())) {
            return false;
          }
          if (!getUnknownFields().equals(other.getUnknownFields())) {
            return false;
          }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasAnimal()) {
                hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
                hash = (53 * hash) + getAnimal().hashCode();
            }
            hash = (37 * hash) + BREED_FIELD_NUMBER;
            hash = (53 * hash) + getBreed().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseDelimitedFrom(
            java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.example.webfluxStudy.entity.protoExample.Inheritance1.Dog}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.example.webfluxStudy.entity.protoExample.Inheritance1.Dog)
            com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.DogOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog.class,
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog.Builder.class);
            }

            // Construct using com.example.webfluxStudy.entity.protoExample.Inheritance1.Inheritance1.Dog.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                    getAnimalFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                animal_ = null;
                if (animalBuilder_ != null) {
                    animalBuilder_.dispose();
                    animalBuilder_ = null;
                }
                breed_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_descriptor;
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog getDefaultInstanceForType() {
                return com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog.getDefaultInstance();
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog build() {
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog buildPartial() {
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog result = new com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog(
                    this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog result) {
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.animal_ = animalBuilder_ == null
                        ? animal_
                        : animalBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.breed_ = breed_;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog) {
                    return mergeFrom(
                        (com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog other) {
              if (other
                  == com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog.getDefaultInstance()) {
                return this;
              }
                if (other.hasAnimal()) {
                    mergeAnimal(other.getAnimal());
                }
                if (!other.getBreed().isEmpty()) {
                    breed_ = other.breed_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                input.readMessage(
                                    getAnimalFieldBuilder().getBuilder(),
                                    extensionRegistry);
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                breed_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal animal_;
            private com.google.protobuf.SingleFieldBuilderV3<
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder> animalBuilder_;

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             *
             * @return Whether the animal field is set.
             */
            public boolean hasAnimal() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             *
             * @return The animal.
             */
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal getAnimal() {
                if (animalBuilder_ == null) {
                    return animal_ == null
                        ? com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()
                        : animal_;
                } else {
                    return animalBuilder_.getMessage();
                }
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public Builder setAnimal(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal value) {
                if (animalBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    animal_ = value;
                } else {
                    animalBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public Builder setAnimal(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder builderForValue) {
                if (animalBuilder_ == null) {
                    animal_ = builderForValue.build();
                } else {
                    animalBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public Builder mergeAnimal(
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal value) {
                if (animalBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0) &&
                        animal_ != null &&
                        animal_
                            != com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()) {
                        getAnimalBuilder().mergeFrom(value);
                    } else {
                        animal_ = value;
                    }
                } else {
                    animalBuilder_.mergeFrom(value);
                }
                if (animal_ != null) {
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public Builder clearAnimal() {
                bitField0_ = (bitField0_ & ~0x00000001);
                animal_ = null;
                if (animalBuilder_ != null) {
                    animalBuilder_.dispose();
                    animalBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder getAnimalBuilder() {
                bitField0_ |= 0x00000001;
                onChanged();
                return getAnimalFieldBuilder().getBuilder();
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder getAnimalOrBuilder() {
                if (animalBuilder_ != null) {
                    return animalBuilder_.getMessageOrBuilder();
                } else {
                    return animal_ == null ?
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.getDefaultInstance()
                        : animal_;
                }
            }

            /**
             * <code>.com.example.webfluxStudy.entity.protoExample.Inheritance1.Animal animal =
             * 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder>
            getAnimalFieldBuilder() {
                if (animalBuilder_ == null) {
                    animalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Animal.Builder, com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.AnimalOrBuilder>(
                        getAnimal(),
                        getParentForChildren(),
                        isClean());
                    animal_ = null;
                }
                return animalBuilder_;
            }

            private java.lang.Object breed_ = "";

            /**
             * <code>string breed = 2;</code>
             *
             * @return The breed.
             */
            public java.lang.String getBreed() {
                java.lang.Object ref = breed_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    breed_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string breed = 2;</code>
             *
             * @return The bytes for breed.
             */
            public com.google.protobuf.ByteString
            getBreedBytes() {
                java.lang.Object ref = breed_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    breed_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string breed = 2;</code>
             *
             * @param value The breed to set.
             * @return This builder for chaining.
             */
            public Builder setBreed(
                java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                breed_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string breed = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearBreed() {
                breed_ = getDefaultInstance().getBreed();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <code>string breed = 2;</code>
             *
             * @param value The bytes for breed to set.
             * @return This builder for chaining.
             */
            public Builder setBreedBytes(
                com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                breed_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:com.example.webfluxStudy.entity.protoExample.Inheritance1.Dog)
        }

        // @@protoc_insertion_point(class_scope:com.example.webfluxStudy.entity.protoExample.Inheritance1.Dog)
        private static final com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog();
        }

        public static com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Dog>
            PARSER = new com.google.protobuf.AbstractParser<Dog>() {
            @java.lang.Override
            public Dog parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException()
                        .setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Dog> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Dog> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.example.webfluxStudy.entity.protoExample.Inheritance.Inheritance1.Dog getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\022inheritance1.proto\0229com.example.webflu" +
                "xStudy.entity.protoExample.Inheritance1\"" +
                "\026\n\006Animal\022\014\n\004name\030\001 \001(\t\"j\n\004Bird\022Q\n\006anima" +
                "l\030\001 \001(\0132A.com.example.webfluxStudy.entit" +
                "y.protoExample.Inheritance1.Animal\022\017\n\007ca" +
                "n_fly\030\002 \001(\010\"g\n\003Dog\022Q\n\006animal\030\001 \001(\0132A.com" +
                ".example.webfluxStudy.entity.protoExampl" +
                "e.Inheritance1.Animal\022\r\n\005breed\030\002 \001(\tb\006pr" +
                "oto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[]{
                });
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Animal_descriptor,
            new java.lang.String[]{"Name",});
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_descriptor =
            getDescriptor().getMessageTypes().get(1);
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Bird_descriptor,
            new java.lang.String[]{"Animal", "CanFly",});
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_descriptor =
            getDescriptor().getMessageTypes().get(2);
        internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_example_webfluxStudy_entity_protoExample_Inheritance1_Dog_descriptor,
            new java.lang.String[]{"Animal", "Breed",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
